/**
 * Measurement harness.
 *
 * The review's required addition #4: ship the numbers the design asserts as
 * MEASURED, or ship the cell visibly empty. Filled-in guesses get treated as
 * spec by whoever implements them.
 *
 * This measures everything measurable without radio hardware — wire sizes,
 * reconciliation round trips and overhead, and crypto throughput. It ends by
 * printing, explicitly, the things it CANNOT measure here, so those stay
 * visibly open rather than quietly plausible.
 *
 *   node packages/courier-core/bench/measure.ts [--md]
 */

import {
  RecordStore,
  reconcile,
  storesConverged,
  makeRecord,
  sealRecord,
  openEnvelope,
  envelopeSize,
  encodeRecord,
  generateDeviceKey,
  generateMeshKey,
  mintScoutPseudonym,
  parseMatchKey,
  type DeviceKeyPair,
  type KeyResolver,
} from '../src/index.ts';
import { toHex } from '../src/hash.ts';

const asMarkdown = process.argv.includes('--md');
const out: string[] = [];
const say = (s = ''): void => {
  out.push(s);
};

/* ------------------------------------------------------------- fixtures --- */

const meshKey = generateMeshKey();
const devices = new Map<string, DeviceKeyPair>();
function device(name: string): DeviceKeyPair {
  let d = devices.get(name);
  if (!d) {
    d = generateDeviceKey('software');
    devices.set(name, d);
  }
  return d;
}
const resolver: KeyResolver = (kid) => {
  for (const d of devices.values()) if (toHex(d.kid) === toHex(kid)) return d.publicKey;
  return undefined;
};

function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s ^= s << 13;
    s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5;
    s >>>= 0;
    return s / 0x100000000;
  };
}

const EVENT = '2027mose';
const TEAMS = [8793, 9143, 254, 1678, 118, 2056, 3128, 5940];

function sealOne(scout: number, match: number, bodyLen: number, rand: () => number): Uint8Array {
  const body = new Uint8Array(bodyLen);
  for (let i = 0; i < bodyLen; i++) body[i] = Math.floor(rand() * 256);
  const record = makeRecord({
    eventKey: EVENT,
    match: parseMatchKey(`${EVENT}_qm${match}`).packed,
    team: TEAMS[(match + scout) % TEAMS.length]!,
    scout: mintScoutPseudonym(`scout-${scout}`, EVENT, meshKey),
    schema: 'demo.scout.v1',
    body,
    sealedAt: 1_800_000_000_000 + match * 1000 + scout,
  });
  return sealRecord(record, device(`tablet-${scout}`));
}

/** Build a store of `matches x scouts` records, omitting indices in `skip`. */
function buildStore(matches: number, scouts: number, seed: number, skip?: Set<number>): RecordStore {
  const store = new RecordStore();
  const rand = rng(seed);
  let i = 0;
  for (let m = 1; m <= matches; m++) {
    for (let s = 0; s < scouts; s++) {
      const len = 40 + Math.floor(rand() * 80);
      i++;
      if (skip?.has(i)) continue;
      store.admit(sealOne(s, m, len, rng(seed * 1000 + i)), resolver);
    }
  }
  return store;
}

/* --------------------------------------------------------------- report --- */

say('# Measured numbers');
say();
say(
  '_Generated by `npm run measure`. Every figure below was produced by running the code, ' +
    'not by estimating. The final section lists what this harness **cannot** measure — those ' +
    'stay open rather than being filled with plausible values._',
);
say();
say(`Node ${process.version} · ${process.platform}/${process.arch}`);
say();

/* 1. Envelope size ---------------------------------------------------------- */

say('## 1. Envelope size vs body size');
say();
say('| Body bytes | Record payload | Envelope | Overhead |');
say('|---:|---:|---:|---:|');
const rand1 = rng(42);
for (const bodyLen of [0, 16, 40, 80, 120, 256, 1024]) {
  const body = new Uint8Array(bodyLen);
  for (let i = 0; i < bodyLen; i++) body[i] = Math.floor(rand1() * 256);
  const record = makeRecord({
    eventKey: EVENT,
    match: parseMatchKey(`${EVENT}_qm1`).packed,
    team: 8793,
    scout: mintScoutPseudonym('scout-0', EVENT, meshKey),
    schema: 'demo.scout.v1',
    body,
    sealedAt: 1_800_000_000_000,
  });
  const env = sealRecord(record, device('tablet-0'));
  const payload = encodeRecord(record).length;
  if (envelopeSize(record) !== env.length) {
    throw new Error(`estimator drift: ${envelopeSize(record)} != ${env.length}`);
  }
  say(`| ${bodyLen} | ${payload} | ${env.length} | ${env.length - bodyLen} |`);
}
say();
say(
  'Overhead is 186-191 bytes and steps only where CBOR length headers widen (186 below a 24-byte ' +
    'body, 188 below 256, 191 beyond). It is 101 bytes of record fields — dominated by two ' +
    '32-byte hashes — plus 21 bytes of COSE structure and a 64-byte Ed25519 signature. That is ' +
    'the price of every record being independently verifiable, which is what lets a device accept ' +
    'a record relayed by a peer it has no reason to trust.',
);
say();

/* 2. Event-day volume ------------------------------------------------------- */

say('## 2. A full event day');
say();
const t0 = performance.now();
const full = buildStore(80, 8, 5);
const buildMs = performance.now() - t0;
const stats = full.stats();
say('| Quantity | Value |');
say('|---|---:|');
say(`| Records (80 quals x 8 scouts) | ${stats.records} |`);
say(`| Distinct observations | ${stats.observations} |`);
say(`| Distinct scouts | ${stats.scouts} |`);
say(`| Total envelope bytes | ${(stats.bytes / 1024).toFixed(1)} kB |`);
say(`| Mean envelope | ${Math.round(stats.bytes / stats.records)} B |`);
say(`| Seal + verify + store, wall clock | ${buildMs.toFixed(0)} ms |`);
say(`| Per record | ${(buildMs / stats.records).toFixed(2)} ms |`);
say();
const kB = stats.bytes / 1024;
say('Transfer time for the whole day\'s data, at the throughput figures the design uses:');
say();
say('| Path | Assumed rate | Time for full day |');
say('|---|---:|---:|');
for (const [name, rate] of [
  ['BLE GATT, iOS peripheral (design figure)', 12],
  ['BLE GATT, Android central (design figure)', 25],
  ['USB mass storage', 5000],
] as const) {
  const secs = kB / rate;
  say(`| ${name} | ${rate} kB/s | ${secs < 1 ? `${(secs * 1000).toFixed(0)} ms` : `${secs.toFixed(1)} s`} |`);
}
say();
say(
  'Bandwidth is not the constraint. A full competition day of scouting moves in well under a ' +
    'minute even on the slowest assumed path — which is the measured basis for cutting L2CAP ' +
    'from v1 (D-13). Connection setup and radio duty cycle are what matter.',
);
say();

/* 3. Reconciliation --------------------------------------------------------- */

say('## 3. Reconciliation cost vs symmetric difference');
say();
say(
  'Two stores, 640 records each at full overlap, then diverged by the stated amount ' +
    '(half missing from each side). "Overhead" excludes the transferred records themselves — ' +
    'it is what the protocol costs to *find* the difference.',
);
say();
say('| Symmetric difference | Messages | Round trips | Total bytes | Protocol overhead | Converged |');
say('|---:|---:|---:|---:|---:|---|');

const RECORD_BYTES = Math.round(stats.bytes / stats.records);
for (const diff of [0, 2, 10, 50, 100, 200, 400]) {
  const half = Math.floor(diff / 2);
  const skipA = new Set<number>();
  const skipB = new Set<number>();
  for (let i = 0; i < half; i++) skipA.add(100 + i);
  for (let i = 0; i < diff - half; i++) skipB.add(300 + i);

  const a = buildStore(80, 8, 5, skipA);
  const b = buildStore(80, 8, 5, skipB);
  const res = reconcile(a, b, resolver);
  const overhead = res.bytes - res.admitted * RECORD_BYTES;
  say(
    `| ${diff} | ${res.rounds} | ${Math.ceil(res.rounds / 2)} | ${(res.bytes / 1024).toFixed(1)} kB | ` +
      `${(Math.max(0, overhead) / 1024).toFixed(1)} kB | ${
        res.converged && storesConverged(a, b) ? 'yes' : 'NO'
      } |`,
  );
}
say();
say(
  'Round trips stay flat as the difference grows, which is the property that matters on a ' +
    'transport where each round trip costs ~1.8 s of connection setup. Protocol overhead is ' +
    'dominated by the one truncated-id list (8 bytes per record held), so it scales with store ' +
    'size rather than difference size — the deliberate trade made by `LEAF_THRESHOLD` (2048), ' +
    'which buys a round trip with a few kB.',
);
say();

/* 4. Crypto throughput ------------------------------------------------------ */

say('## 4. Crypto throughput');
say();
const body = new Uint8Array(80).fill(7);
const rec = makeRecord({
  eventKey: EVENT,
  match: parseMatchKey(`${EVENT}_qm1`).packed,
  team: 8793,
  scout: mintScoutPseudonym('scout-0', EVENT, meshKey),
  schema: 'demo.scout.v1',
  body,
  sealedAt: 1_800_000_000_000,
});
const dev = device('tablet-0');

const N = 500;
const ts = performance.now();
for (let i = 0; i < N; i++) sealRecord(rec, dev);
const signMs = (performance.now() - ts) / N;

const env = sealRecord(rec, dev);
const tv = performance.now();
for (let i = 0; i < N; i++) openEnvelope(env, resolver);
const verifyMs = (performance.now() - tv) / N;

say('| Operation | Per record | Records/second |');
say('|---|---:|---:|');
say(`| Seal (encode + Ed25519 sign) | ${signMs.toFixed(2)} ms | ${Math.round(1000 / signMs)} |`);
say(`| Open (verify + decode + validate) | ${verifyMs.toFixed(2)} ms | ${Math.round(1000 / verifyMs)} |`);
say();
say(
  `On this machine a peer can verify a full event day (${stats.records} records) in ` +
    `${((verifyMs * stats.records) / 1000).toFixed(1)} s. A 2016-class Chromebook or a low-end ` +
    'Android tablet should be assumed several times slower — see the open items below, because ' +
    'that factor has not been measured on real hardware.',
);
say();

/* 5. What this cannot measure ---------------------------------------------- */

say('## 5. Not measured here — these cells stay empty on purpose');
say();
say('| Open question | Why this harness cannot answer it | Blocks |');
say('|---|---|---|');
for (const [q, why, blocks] of [
  [
    'Real BLE sustained throughput, GATT peripheral role',
    'Needs two physical devices and a radio; the 12 / 25 kB/s figures above are the design\'s assumptions, carried through, not measurements',
    'NFR-3, NFR-4',
  ],
  [
    'iOS `updateValue` backpressure',
    'Requires an iOS peripheral under load; the failure mode (second and later notifications returning false, ready-callback stalling 50-100 ms) is invisible in a simulator',
    'iOS throughput, NFR-3',
  ],
  [
    'Connection setup time, device to device',
    'Radio-dependent; the ~1.8 s used in the LEAF_THRESHOLD derivation is an assumption and the whole threshold rests on it',
    'LEAF_THRESHOLD, D-11',
  ],
  [
    'Battery cost of a full event day of gossip',
    'Needs a real device and a real radio duty cycle; D-21 explicitly leaves this to be re-derived after D-11 changed the schedule',
    'NFR-1, D-21',
  ],
  [
    'ChromeOS BLE advertising capability',
    'Platform capability question, not a protocol one — and it decides whether a rookie team with only Chromebooks can form a mesh at all',
    'The rookie persona',
  ],
  [
    'Verify throughput on 2016-class hardware',
    'This machine is not the target device; the ratio to a Celeron N3060 Chromebook is unknown',
    'NFR-6, catch-up time',
  ],
] as const) {
  say(`| ${q} | ${why} | ${blocks} |`);
}
say();

const text = out.join('\n');
if (asMarkdown) {
  process.stdout.write(text + '\n');
} else {
  process.stdout.write(text.replace(/\|/g, ' ') + '\n');
}
